[package]
name = "easyIDEP"
version = "0.1.0"
authors = ["kokoax <yomo4808@gmail.com>"]

[dependencies]
regex = "0.2"
sourceview = "0.1.3"
gdk="0.5.3"
glib-sys="0.3.4"
cairo-sys-rs="0.3.4"

[dependencies.gtk]
version = "0.1.3"
features = ["v3_16"]

